version: '3.8'
services:
  db:
    image: postgres
    container_name: s3explorer-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - local.db.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    container_name: s3explorer-pgadmin
    restart: always
    ports:
      - '8888:80'
    env_file:
      - local.db.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres
  
  cache:
    image: redis:7-alpine
    container_name: s3-redis-cache
    restart: always
    build:
      dockerfile: Dockerfile.redis
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    
      
volumes:
  db_data:
  pgadmin_data:
  cache:
    driver: local

networks:
  postgres:
    driver: bridge
