version: '3.8'
services:
  db:
    image: postgres
    container_name: s3spider-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - local.db.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    container_name: s3spider-pgadmin
    restart: always
    ports:
      - '8888:80'
    env_file:
      - local.db.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres
  
  cache:
    image: redis:7-alpine
    container_name: s3spider-cache
    restart: always
    build:
      dockerfile: Dockerfile.redis
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - postgres
  
  client:
    image: s3spider-client-img
    container_name: s3spider-client
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  server:
    image: s3spider-server-img
    container_name: s3spider-server
    depends_on:
      - db
      - cache
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - server/.env
    networks:
      - postgres
      
volumes:
  db_data:
  pgadmin_data:
  cache:
    driver: local

networks:
  postgres:
    driver: bridge
